name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main
      - v*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/v')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Deploy to SageMaker
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        # Add SageMaker deployment steps here
        # Example:
        python scripts/train_model.py --input-data s3://your-bucket-name/path_to_your_training_data --model-output models/xgboost_model.joblib
        python scripts/predict.py --input-data s3://your-bucket-name/path_to_your_test_data --model-path models/xgboost_model.joblib --output-file predictions.csv
